### ISSUE TITLE
Make this library installable via composer

### ISSUE THREAD

**Issue by lexidor** [hhvm/hhast-inspect#1]
The package has not been published to [packagist](https://packagist.org/?query=hhvm%2Fhhast).
`composer require --dev hhvm/hhast-inspect` can therefore not find this package.

**Comment by fredemmott** [comment]
Added, however having a bit of trouble getting the auto-update/sync configured.

**Comment by fredemmott** [comment]
Composer picked up that change so the integration is working :)
